import Head from 'next/head'
// import AboutUsFeatures from '../component/AboutUsFeatures'
// import AboutUsMission from '../component/AboutUsMission'
// import CounterSection from '../component/CounterSection'
import Layout from '../component/Layout'
import SliderAbout from '../component/SliderAbout'

export default function About() {
  return (
    <>
      <Head>
        <title>Ghoroya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SliderAbout />
      <Layout>
        {/* <AboutUsMission /> */}
        {/* <AboutUsFeatures /> */}
        {/* <CounterSection /> */}
      </Layout>
    </>
  )
}
