import Head from 'next/head'
import CounterSection from '../component/CounterSection'
import FoodOrder from '../component/FoodOrder'
import HomeAppScreen from '../component/HomeAppScreen'
import HowItWork from '../component/HowItWork'
import Layout from '../component/Layout'
import Slider from '../component/Slider'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ghoroya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Slider />
        <HowItWork />
        <HomeAppScreen />
        <FoodOrder />
        <CounterSection />
      </Layout>
    </>
  )
}
